# Generated by Django 5.0 on 2024-02-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_checkpoints', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
    ]
